import 'package:cached_network_image/cached_network_image.dart';
import 'package:easy_localization/easy_localization.dart';
import 'package:flutter/material.dart';
import 'package:flutter_icons/flutter_icons.dart';
import 'package:flutter_staggered_grid_view/flutter_staggered_grid_view.dart';
import 'package:flutter_svg/flutter_svg.dart';
import 'package:get/get.dart';
import 'package:readmore/readmore.dart';
import 'package:simple_animations/simple_animations.dart';
import 'package:smooth_star_rating/smooth_star_rating.dart';
import 'package:path/path.dart';

import '../helpers/helpers.dart';
import '../models/models.dart';
import '../models/wishListArray.dart';

import '../pages/pages.dart';
import 'package:http/http.dart' as http;
import 'dart:convert';
part 'src/activity_card_widget.dart';
part 'src/category_circle_widget.dart';
part 'src/facebook_sign_in_button_widget.dart';
part 'src/fade_animation.dart';
part 'src/feed_card_widget.dart';
part 'src/google_sign_in_button_widget.dart';
part 'src/horizontal_list_widget.dart';
part 'src/offer_card_widget.dart';
part 'src/product_card_widget.dart';
part 'src/ProductCard2.dart';

part 'src/product_grid_card_widget.dart';
part 'src/raised_button_widget.dart';
part 'src/review_card_widget.dart';
part 'src/side_animation.dart';
part 'src/text_field_widget.dart';
part 'src/text_form_field_widget.dart';
part 'src/vertical_list_widget.dart';
part 'src/cart_card_widget.dart';
part 'src/counter_widget.dart';
part 'src/address_card_widget.dart';
part 'src/payment_card_widget.dart';
part 'src/order_card_widget.dart';
part 'src/dropdown_widget.dart';
part 'src/loginvalidation.dart';
